spring:
  datasource:
    url: jdbc:postgresql://localhost:15432/car_rest
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1234
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration



server:
  port: 8080
  servlet:
    context-path: /api/v1

logging:
  level:
    org.springframework.security: DEBUG


springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

  security:
    oauth2:
      resourceserver:
        jwt:
          audiences: https://api
          issuer-uri: https://dev-ko34gcgbvolph12u.us.auth0.com/
      client:
        registration:
          auth0:
            client-id: jj2FBUDjUdNmbDgx4uvj9TQWzTv11uUz
            client-secret: ukRnOPUuiEYhcMig1mZQ5Hhp5jgxiloW4Kkn32wCMR_zyJYAzmBjmNsy7mjtSXml
            authorization-grant-type: client_credentials
        provider:
          auth0:
            issuer-uri: https://dev-ko34gcgbvolph12u.us.auth0.com/